#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check EsLint
npm run lint || 
{
    echo 'EsLint check failed. Make the require changes linted above, add changes and try to commit again';
    false;
}

echo "Success Commit"